baseURL = "https://www.rszin.com/"
   languageCode = "en-us"
   title = "Ariel Szin"
   theme = "dario"

   [params]
     author = "Ariel Szin"
     description = "Questions,Exploratory Musings"

     [params.homeInfoParams]
#       Title = "Welcome to My Website"
       Content = "Questions, Exploratory Musings, Projects"
       Description = "A minimal web log."